[update]
tasks = ["interfaces", "code", "transform", "normalize"]

[update.interfaces]
paths = [.,"He3","He3/Support
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.transform]
codePaths = [.,"He3","He3/Support"]
localizablePaths = [.,"He3","He3/Support"]
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
paths = [.,"He3","He3/Support"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = [.,"He3","He3/Support"]
duplicateKeys = true
emptyValues = true
